[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' https://fonts.gstatic.com https://fonts.googleapis.com; connect-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; frame-src 'self';"
    Access-Control-Allow-Origin = "*"
